---
server:
  port: 8990

spring:
  application:
    name: turbine
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  aggregator:
    clusterConfig: CLOUD-SIMPLE-SERVICE
  appConfig: cloud-simple-service
  clusterNameExpression: metadata['cluster']